<?php
namespace OAuth2Provider\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthRefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthRefreshTokenRepository extends EntityRepository
{
}
