<?php
namespace OAuth2Provider\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthClientRepository extends EntityRepository
{
    public function getClientDetails($clientId)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('c.clientId, c.redirectUri, c.grantTypes')
            ->from($this->_entityName, 'c')
            ->where('c.clientId = ?1')
            ->setParameter(1, $clientId);
        //$r = $qb->getQuery()->getSQL();
        //var_dump($r);die;

        return $qb->getQuery()->getSingleResult();
    }
}
