<?php

namespace ApiOAuthProvider\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthUsers
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthUsers extends EntityRepository
{
}
